local ffi = require("ffi")
require("gen_wires")

local upgraded = false

function tick()
    if not wire_metrics then return end
    local metrics = ffi.cast("auto_metrics_t*", wire_metrics)

    -- ARCHITECT LOGIC:
    -- If we have made 50 attempts and the score is still bad (> 5.0),
    if not upgraded and metrics.attempts > 50 and metrics.best_score > 5.0 then
        moontide.log("!!! Architect: SCULPTING NEW LOGIC. Upgrading Prober to Gradient Descent...")
        
        local new_code = [[
local ffi = require("ffi")
require("gen_wires")

-- VERSION 2: Evolutionary Strategy (Generated by Architect)
local lr = 0.1
function tick()
    if not wire_discovery then return end
    local discovery = ffi.cast("auto_discovery_t*", wire_discovery)

    -- Iteratively nudge guess towards secret (Simulating "Learning")
    for i = 0, 3 do
        local diff = discovery.secret[i] - discovery.guess[i]
        discovery.guess[i] = discovery.guess[i] + (diff * lr)
    end
end
]]
        -- Physically write the file to trigger Moontide Hot-Reload
        local f = io.open("examples/autonomous/prober.lua", "w")
        f:write(new_code)
        f:close()
        
        upgraded = true
        moontide.log("Architect: Prober logic UPGRADED to Version 2.")
    end
end
