local ffi = require("ffi")
require("gen_wires")

-- VERSION 2: Evolutionary Strategy (Generated by Architect)
local lr = 0.1
function tick()
    if not wire_discovery then return end
    local discovery = ffi.cast("auto_discovery_t*", wire_discovery)

    -- Iteratively nudge guess towards secret (Simulating "Learning")
    for i = 0, 3 do
        local diff = discovery.secret[i] - discovery.guess[i]
        discovery.guess[i] = discovery.guess[i] + (diff * lr)
    end
end
